javac ./hadoop-mapreduce-client-app/src/test/java/org/apache/hadoop/mapreduce/v2/app/Replicate.java\
 ./hadoop-mapreduce-client-app/src/test/java/org/apache/hadoop/mapreduce/v2/app/MRApp.java -cp \
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/commons-logging-1.1.1.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/junit-4.10.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/mockito-all-1.8.5.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-common-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-mapreduce-client-common-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-mapreduce-client-core-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-mapreduce-client-jobclient-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-mapreduce-client-app-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-mapreduce-client-shuffle-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-mapreduce-client-hs-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-yarn-common-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-yarn-server-common-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-yarn-server-nodemanager-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-yarn-server-resourcemanager-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-yarn-server-web-proxy-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-yarn-api-2.0.0-alpha.jar


java -cp .\
:./hadoop-mapreduce-client-app/src/test/java/\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/junit-4.10.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/netty-3.2.10.Final.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/avro-1.7.0.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/mockito-all-1.8.5.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/commons-logging-1.1.1.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/slf4j-api-1.7.0.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/slf4j-simple-1.7.0.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/mockito-all-1.8.5.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/guava-15.0.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/protobuf-java-2.6.0.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/log4j-1.2.17.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-common-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/commons-configuration-1.10.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/commons-lang-2.6.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-auth-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-mapreduce-client-common-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-mapreduce-client-core-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-mapreduce-client-jobclient-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-mapreduce-client-app-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-mapreduce-client-shuffle-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-mapreduce-client-hs-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-yarn-common-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-yarn-server-common-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-yarn-server-nodemanager-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-yarn-server-resourcemanager-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-yarn-server-web-proxy-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/hadoop-yarn-api-2.0.0-alpha.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/jackson-core-asl-1.9.13.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/jackson-mapper-asl-1.9.13.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/guice-servlet-4.0.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/guice-4.0.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/jetty-6.1.15.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/jetty-util-6.1.15.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/javax.servlet-api-4.0.1.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/javax.inject-1.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/aopalliance-1.0.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/javax.ws.rs-api-2.0.1.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/jersey-client-1.18.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/jersey-core-1.18.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/jersey-server-1.18.jar\
:/Users/caohch1/Projects/bug-data/MP-4637/dependency/jersey-guice-1.18.jar\
 org.apache.hadoop.mapreduce.v2.app.Replicate