spring:

  application:
    name: ts-sso-service

  data:
    mongodb:
      host: ts-account-mongo
      database: ts
      port: 27017
  redis:
    host: ts-sso-redis
    port: 6379

  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0

  

# HTTP Server
server:
  port: 12349  # HTTP (Tomcat) port