server:
  port: 16112

spring:
  application:
    name: ts-admin-order-service
  redis:
    host: redis
    port: 6379
  zipkin:
    baseUrl: http://zipkin:9411/
  sleuth:
    sampler:
      percentage: 1.0

